---
- name: Import cleanup tasks
  ansible.builtin.import_tasks: cleanup.yml
  when: systemd_networkd_cleanup | bool

- name: Import config tasks
  ansible.builtin.import_tasks: config.yml

- name: Make sure systemd-resolved is installed
  become: true
  ansible.builtin.package:
    name: systemd-resolved
    state: present
  when:
    - ansible_facts.distribution | lower == 'debian'
    - ansible_facts.distribution_major_version >= '12'

- name: Enable systemd-networkd
  become: true
  when: systemd_networkd_network or systemd_networkd_link or systemd_networkd_netdev
  block:
    # TODO(mattcrees): Remove once this gets into a versioned release:
    # https://github.com/ansible/ansible/pull/77754
    - name: Temporarily disable systemd-networkd
      ansible.builtin.service:
        name: systemd-networkd
        enabled: false

    - name: Enable systemd-networkd
      ansible.builtin.service:
        name: systemd-networkd
        enabled: true

- name: Start and enable systemd-resolved
  become: true
  ansible.builtin.service:
    name: systemd-resolved
    enabled: true
    state: started
  when: systemd_networkd_enable_resolved

- name: Replace /etc/resolv.conf with a symlink to the systemd-resolved stub
  become: true
  ansible.builtin.file:
    path: /etc/resolv.conf
    src: /run/systemd/resolve/stub-resolv.conf
    state: link
    force: true
  when: systemd_networkd_symlink_resolv_conf

# vim: set ts=2 sw=2:
