---
# By default, Ubuntu's configuration permits:
#   - Responding to ARP requests with addresses from other interfaces (arp_filter=0)
#   - Reply for any local target IP address, configured on any interface (arp_ignore=0)
# This behaviour breaks RoCE when a host has multiple interfaces in the same network.
- name: Configure sysctl with ARP settings
  ansible.builtin.copy:
    dest: /etc/sysctl.d/15-fixarp.conf
    content: |
      net.ipv4.conf.all.arp_ignore=1
      net.ipv4.conf.all.arp_announce=2
    mode: "0644"
    owner: root
    group: root
  when:
    - ansible_facts.os_family == "Debian"
    - ansible_facts.distribution == "Ubuntu"
  notify:
    - Restart for arp change
